// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Painting struct {
	ID          int32
	Title       string
	Description sql.NullString
	Style       string
	Medium      sql.NullString
	ImageUrl    string
	Size        sql.NullString
	Price       sql.NullString
	Featured    bool
	CreatedAt   sql.NullTime
}

type CommissionRequest struct {
	ID              int32
	Name            string
	Email           string
	Phone           sql.NullString
	Style           string
	Description     string
	SpecialRequests sql.NullString
	Status          sql.NullString
	CreatedAt       sql.NullTime
}

type ReferenceImage struct {
	ID           int32
	CommissionID int32
	ImageUrl     string
	CreatedAt    sql.NullTime
}
