// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getAllPaintings = `-- name: GetAllPaintings :many
SELECT id, title, description, style, medium, image_url, size, price, featured, created_at FROM paintings ORDER BY created_at DESC
`

func (q *Queries) GetAllPaintings(ctx context.Context) ([]Painting, error) {
	rows, err := q.db.QueryContext(ctx, getAllPaintings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Painting
	for rows.Next() {
		var i Painting
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Style,
			&i.Medium,
			&i.ImageUrl,
			&i.Size,
			&i.Price,
			&i.Featured,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaintingsByStyle = `-- name: GetPaintingsByStyle :many
SELECT id, title, description, style, medium, image_url, size, price, featured, created_at FROM paintings WHERE style = ? ORDER BY created_at DESC
`

func (q *Queries) GetPaintingsByStyle(ctx context.Context, style string) ([]Painting, error) {
	rows, err := q.db.QueryContext(ctx, getPaintingsByStyle, style)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Painting
	for rows.Next() {
		var i Painting
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Style,
			&i.Medium,
			&i.ImageUrl,
			&i.Size,
			&i.Price,
			&i.Featured,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedPaintings = `-- name: GetFeaturedPaintings :many
SELECT id, title, description, style, medium, image_url, size, price, featured, created_at FROM paintings WHERE featured = TRUE ORDER BY created_at DESC
`

func (q *Queries) GetFeaturedPaintings(ctx context.Context) ([]Painting, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedPaintings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Painting
	for rows.Next() {
		var i Painting
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Style,
			&i.Medium,
			&i.ImageUrl,
			&i.Size,
			&i.Price,
			&i.Featured,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaintingByID = `-- name: GetPaintingByID :one
SELECT id, title, description, style, medium, image_url, size, price, featured, created_at FROM paintings WHERE id = ?
`

func (q *Queries) GetPaintingByID(ctx context.Context, id int32) (Painting, error) {
	row := q.db.QueryRowContext(ctx, getPaintingByID, id)
	var i Painting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Style,
		&i.Medium,
		&i.ImageUrl,
		&i.Size,
		&i.Price,
		&i.Featured,
		&i.CreatedAt,
	)
	return i, err
}

const createPainting = `-- name: CreatePainting :execresult
INSERT INTO paintings (title, description, style, medium, image_url, size, price, featured)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePaintingParams struct {
	Title       string
	Description sql.NullString
	Style       string
	Medium      sql.NullString
	ImageUrl    string
	Size        sql.NullString
	Price       sql.NullString
	Featured    bool
}

func (q *Queries) CreatePainting(ctx context.Context, arg CreatePaintingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPainting,
		arg.Title,
		arg.Description,
		arg.Style,
		arg.Medium,
		arg.ImageUrl,
		arg.Size,
		arg.Price,
		arg.Featured,
	)
}

const updatePainting = `-- name: UpdatePainting :exec
UPDATE paintings SET title = ?, description = ?, style = ?, medium = ?, size = ? WHERE id = ?
`

type UpdatePaintingParams struct {
	Title       string
	Description sql.NullString
	Style       string
	Medium      sql.NullString
	Size        sql.NullString
	ID          int32
}

func (q *Queries) UpdatePainting(ctx context.Context, arg UpdatePaintingParams) error {
	_, err := q.db.ExecContext(ctx, updatePainting,
		arg.Title,
		arg.Description,
		arg.Style,
		arg.Medium,
		arg.Size,
		arg.ID,
	)
	return err
}

const deletePainting = `-- name: DeletePainting :exec
DELETE FROM paintings WHERE id = ?
`

func (q *Queries) DeletePainting(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePainting, id)
	return err
}

const createCommission = `-- name: CreateCommission :execresult
INSERT INTO commission_requests (name, email, phone, style, description, special_requests)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCommissionParams struct {
	Name            string
	Email           string
	Phone           sql.NullString
	Style           string
	Description     string
	SpecialRequests sql.NullString
}

func (q *Queries) CreateCommission(ctx context.Context, arg CreateCommissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCommission,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Style,
		arg.Description,
		arg.SpecialRequests,
	)
}

const getAllCommissions = `-- name: GetAllCommissions :many
SELECT id, name, email, phone, style, description, special_requests, status, created_at FROM commission_requests ORDER BY created_at DESC
`

func (q *Queries) GetAllCommissions(ctx context.Context) ([]CommissionRequest, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommissionRequest
	for rows.Next() {
		var i CommissionRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Style,
			&i.Description,
			&i.SpecialRequests,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommissionStatus = `-- name: UpdateCommissionStatus :exec
UPDATE commission_requests SET status = ? WHERE id = ?
`

type UpdateCommissionStatusParams struct {
	Status sql.NullString
	ID     int32
}

func (q *Queries) UpdateCommissionStatus(ctx context.Context, arg UpdateCommissionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCommissionStatus, arg.Status, arg.ID)
	return err
}

const createReferenceImage = `-- name: CreateReferenceImage :execresult
INSERT INTO reference_images (commission_id, image_url)
VALUES (?, ?)
`

type CreateReferenceImageParams struct {
	CommissionID int32
	ImageUrl     string
}

func (q *Queries) CreateReferenceImage(ctx context.Context, arg CreateReferenceImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReferenceImage,
		arg.CommissionID,
		arg.ImageUrl,
	)
}

const getReferenceImagesByCommission = `-- name: GetReferenceImagesByCommission :many
SELECT id, commission_id, image_url, created_at FROM reference_images WHERE commission_id = ? ORDER BY created_at
`

func (q *Queries) GetReferenceImagesByCommission(ctx context.Context, commissionID int32) ([]ReferenceImage, error) {
	rows, err := q.db.QueryContext(ctx, getReferenceImagesByCommission, commissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceImage
	for rows.Next() {
		var i ReferenceImage
		if err := rows.Scan(
			&i.ID,
			&i.CommissionID,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
